apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: novo-deployment
  name: novo-deployment
  namespace: giropops
spec:
  replicas: 10
  selector:
    matchLabels:
      app: novo-deployment
  strategy:
    type: Recreate 
  template:
    metadata:
      labels:
        app: novo-deployment
    spec:
      containers:
      - image: nginx:1.14.0
        name: mginx
        resources:
          limits:
            cpu: 0.5
            memory: 256Mi
          requests:
            cpu: 0.3
            memory: 64Mi
